#!/bin/sh

# chkconfig: 2345 99 00
# description: Seycon Server/Agent
dir=/opt/soffidsyncserver/bin
cmd=./seycon3
prog=seycon3

    case "$1" in
		 start)
            if [ -r /var/lock/subsys/$prog ]
            then
              echo "$prog already running"
              exit 1
            fi
            cd "$dir"
		     eval "$cmd start"
		     touch /var/lock/subsys/$prog
            echo $$ >/var/run/$prog.pgid
		     ;;
		 stop)
            if [ ! -r /var/lock/subsys/$prog ]
            then
              echo "$prog not running"
              exit 1
            fi
            cd "$dir"
		     eval "$cmd stop"
            kill -9 -$(cat /var/run/$prog.pgid)
		     rm -f /var/lock/subsys/$prog
		     ;;
		 *)
		     eval "$cmd $@"
		     ;;
    esac
