// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringServiceLocator.vsl in andromda-spring-cartridge.
//
package es.caib.seycon.ng.sync;

import java.io.FileNotFoundException;
import java.io.IOException;

import org.springframework.jdbc.datasource.DriverManagerDataSource;

import es.caib.seycon.ng.config.Config;

/**
 * Locates and provides all available application services.
 */
public class ServerServiceLocator
{
    static private es.caib.seycon.ng.ServiceLocator baseServiceLocator = null;


    private ServerServiceLocator()
    {
    }

    /**
     * Gets the shared instance of this Class
     *
     * @return the shared service locator instance.
     */
    public static final es.caib.seycon.ng.ServiceLocator instance()
    {
        if (baseServiceLocator == null) {
            baseServiceLocator = es.caib.seycon.ng.ServiceLocator.instance();
            baseServiceLocator.init("localBeanRefFactory.xml", "beanRefFactory");
        }
        return baseServiceLocator;
    }

}